# Generated by Django 6.0.3 on 2026-03-27 07:33

import apps.admission.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(max_length=20)),
                ('civil_status', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('last_school_attended', models.CharField(max_length=255)),
                ('year_completion', models.CharField(max_length=4)),
                ('program', models.CharField(max_length=100)),
                ('strand_or_course', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=50)),
                ('student_status', models.CharField(max_length=50)),
                ('honor', models.CharField(blank=True, default='No Honor', max_length=50)),
                ('apply_scholarship', models.BooleanField(default=False)),
                ('requirements_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=apps.admission.models.admission_requirement_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='admission.admissionapplication')),
            ],
            options={
                'ordering': ['requirement_name'],
                'unique_together': {('application', 'requirement_name')},
            },
        ),
    ]
